### ISSUE TITLE
Allow alternate active selection

### ISSUE THREAD

**Issue by tingerrr** [tingerrr/hydra#13]
Some users have expressed the desire to select the last heading on the current page over what hydra currently considers the active element, if one exists.

**Comment by freundTech** [comment]
Do you have any plans for how the API for that should look?

I would like to try implementing this (actually, I already implemented this functionally without hydra, but I would like to switch to using hydra to simplify my template. I would just have to integrate my code into hydra).

**Comment by tingerrr** [comment]
I'm unsure, at best it would simply be a parameter once can switch like `hydra(latex: true)` (using a bikesheddy name here because I can't think of one) and the function does the rest, but when I looked at it, I didn't find a nice way to change the internal behavior to match.

I've pushed a commit form that attempt that allows disabling the ancestor scoping.

If you find a way to fit this into the API neatly, then go ahead!
