### ISSUE TITLE
Some `show` rules break redundancy check 

### ISSUE THREAD

**Issue by tingerrr** [tingerrr/hydra#2]
With some show rules for vertical spacing on first-level headings, omitting block wrapping breaks the redundancy check. Adding the block back fixes the issue.

```typst
#import "@preview/hydra:0.2.0": hydra

#set page(header: hydra(
  display: (_, it) => {
    if it.numbering != none [
      Chapter #counter(heading).display()
    ]
    it.body
  })
)
#set heading(numbering: "1.1")

// if the block is removed this will no longer check for redundancy correctly,
// some of the spacing also subtly changes.
#show heading.where(level: 1) : it => pagebreak(weak: true) + block({
  set text(2em, weight: "bold")
  v(8em)
  if it.numbering != none [
    Chapter #counter(heading).display()
    #v(.5em)
  ]
  it.body
  v(0.5em)
})

= First
asda

= Second
a

= Third
asd

#pagebreak()

asdas
```

Removing the block will cause each page to reference its next section instead of the last/none.

**Comment by tingerrr** [comment]
It seems that there are a few things at play here:
- leading spacing or styling elements are not considered when creating an element's location
- adding leading spacing will change the position to where ever the next "actual content" starts
- adding a block around this spacing creates a non spacing or style element before this spacing, once again pinning the location back to where it "should be" or at least where hydra expects it

I believe this is intended to make introspection more sensible to the end user, but I will inquire about this. What surprised me is that adding `metadata` before the spacing/styling elements fixed it too, meaning despite being invisible it causes the location to change. This on the other hand seems unintended.

**Comment by tingerrr** [comment]
I'm closing this in favor of a new issue.

**Comment by drupol** [comment]
Which issue?

**Comment by tingerrr** [comment]
I have just created it and linked to it.
