### ISSUE TITLE
Access element of hydra-heading

### ISSUE THREAD

**Issue by roland-KA** [tingerrr/hydra#24]
How can I access the body and the number of the heading that `hydra()` returns?

I've tried e.g. `hydra(1).body` to get only the text of the heading ... but this doesn't work.

**Comment by tingerrr** [comment]
You can configure how to display the heading using the `display` parameter, hydra passes a context dictionary and the appropriate element to this function and returns whatever this function returns. By default, display checks if there is numbering and displays it alongside the body. To only display the body, you could do this:

```typst
#context hydra(1, display: (_, it) => it.body)
```

Unfortunately the docs are a little lackluster atm, I'll improve this in due time.

**Comment by roland-KA** [comment]
Ah thanks, that works fine! 😊

... and hydra is by the way a really nice package! I have the impression that each template author solves these problems again and again (and not so sophisticated as in hydra). So this package is really appreciated!
