### ISSUE TITLE
`skip-starting` has no effect

### ISSUE THREAD

**Issue by roland-KA** [tingerrr/hydra#25]
I've tried the `skip-starting`-parameter. But switching between `true` and `false`  had no effect in my document. 

As to my understanding, switching this parameter to `true` should prevent the display of the heading within the header on those pages, where the respective heading occurs in the text? I.e. `hydra(1, skip-starting: true)` should show an empty header on those pages, where a new chapter starts.

**Comment by tingerrr** [comment]
Do you have show rules which add spacing using `v` instead of `block.spacing`? This changes the heading's location and makes hydra unable to determine a starting page reliably.

**Comment by roland-KA** [comment]
Oh yes, I've the following show-rule:

```typst
#show heading: it => [
  #set text(font: heading-font, fill: blue, weight: "regular")
  #v(1em)
  #block(it)
]
```

So I have to use the `above`-parameter of `block` instead of the `v`-element?

> This changes the heading's location and makes hydra unable to determine a starting page reliably.

It seems to my that Typst needs some improvement for identifying such elements  reliably 😬.

**Comment by roland-KA** [comment]
I've tried now the version without `v`. And indeed it works now. Thanks!
